// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-7SfVtk1BuCaZhsgLaFX8tXRtITCjzc',
    appId: '1:857337256435:web:01c815acdb0bb6cd465a86',
    messagingSenderId: '857337256435',
    projectId: 'movie-queue-c2e96',
    authDomain: 'movie-queue-c2e96.firebaseapp.com',
    storageBucket: 'movie-queue-c2e96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiK9E-d_wPQqj9TTVuPY3_DybFvNHNrak',
    appId: '1:857337256435:android:31bd26914a9b0b28465a86',
    messagingSenderId: '857337256435',
    projectId: 'movie-queue-c2e96',
    storageBucket: 'movie-queue-c2e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhkPZ2OC9qNZKPw6_nOB5kEMzE2Xebi4g',
    appId: '1:857337256435:ios:dc77a196f5170c26465a86',
    messagingSenderId: '857337256435',
    projectId: 'movie-queue-c2e96',
    storageBucket: 'movie-queue-c2e96.firebasestorage.app',
    iosBundleId: 'com.example.movieQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhkPZ2OC9qNZKPw6_nOB5kEMzE2Xebi4g',
    appId: '1:857337256435:ios:dc77a196f5170c26465a86',
    messagingSenderId: '857337256435',
    projectId: 'movie-queue-c2e96',
    storageBucket: 'movie-queue-c2e96.firebasestorage.app',
    iosBundleId: 'com.example.movieQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1-7SfVtk1BuCaZhsgLaFX8tXRtITCjzc',
    appId: '1:857337256435:web:1f0bdbbdb2ccf5e7465a86',
    messagingSenderId: '857337256435',
    projectId: 'movie-queue-c2e96',
    authDomain: 'movie-queue-c2e96.firebaseapp.com',
    storageBucket: 'movie-queue-c2e96.firebasestorage.app',
  );
}
